CREATE TABLE Administrateur (

AdminID INT NOT NULL PRIMARY KEY IDENTITY,

Identifiant NVARCHAR(100) NULL,

Mot_de_passe NVARCHAR(100) NULL

);

CREATE TABLE Adherents (

AdherentID INT NOT NULL PRIMARY KEY IDENTITY,

Nom NVARCHAR(100) NOT NULL,

Prenom NVARCHAR(100) NOT NULL,

Date_naissance DATE NOT NULL,

Email NVARCHAR(100) NOT NULL,

Tel INT NOT NULL,

Adresse NVARCHAR(100) NOT NULL,

Contact_urgenceID INT NOT NULL,

Mot_de_passe NVARCHAR(100) NULL

);

CREATE TABLE Contact_Urgence (

ContactID INT NOT NULL PRIMARY KEY IDENTITY,

Nom NVARCHAR(100) NOT NULL,

Prenom NVARCHAR(100) NOT NULL,

Email NVARCHAR(100) NOT NULL,

Tel INT NOT NULL,

Relation NVARCHAR(100) NOT NULL,

);

CREATE TABLE Activites (

ActiviteID INT NOT NULL PRIMARY KEY IDENTITY,

Sport NVARCHAR(100) NOT NULL,

Section NVARCHAR(100) NOT NULL,

Jour NVARCHAR(100) NOT NULL,

Heure TIME NOT NULL,

Capacite_max INT NOT NULL,

Prix FLOAT NOT NULL,

EmployeID INT NOT NULL,

);

CREATE TABLE Employes (

EmployeID INT NOT NULL PRIMARY KEY IDENTITY,

Nom NVARCHAR(100) NOT NULL,

Prenom NVARCHAR(100) NOT NULL,

Date_naissance DATE NOT NULL,

Email NVARCHAR(100) NOT NULL,

);

CREATE TABLE Inscription (

InscriptionID INT NOT NULL PRIMARY KEY IDENTITY,

AdherentID INT NOT NULL,

ActiviteID INT NOT NULL,

Date_inscription DATE NOT NULL,

AssurancePath NVARCHAR(255) NULL,

CertificatPath NVARCHAR(255) NULL, 

AccordParentalPath NVARCHAR(255) NULL 

);